In [11]:
import requests
import pandas as pd 
import json
key = 'key removed'
address = input("What stadium are you visiting? ")

params = { 'address' : address, 'key' : key}
url = 'https://maps.googleapis.com/maps/api/geocode/json' # geocoding

try: 
    

    response = requests.get(url, params = params)
    location = response.json()
    coords = location['results'][0]['geometry']['location']
    lat = (coords['lat'])
    lng = (coords['lng'])
    coordinates = (lat,lng)

except IndexError:
    print("Please enter a valid stadium. ")
    
key= 'key removed'
search=input("What do you want to find?: ")
print("       ")
url= 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=%s,%s&radius=2500&keyword=%s&key=AIzaSyCdZbZ-Q1ROLoqMU6gMvirPqIu4Sm5FNQc'% (lat,lng, search)

response = requests.get(url, params = params)
output = response.json()
places=output['results']

x = pd.DataFrame(places, columns = ['name','price_level','rating','vicinity'])
print("Welcome to %s! Here are some suggestions of %ss for you to try while you're in the city! " % (address,search))
x.sort_values(by= 'rating', ascending = False)

What stadium are you visiting? Yankee Stadium
What do you want to find?: bar

Welcome to Yankee Stadium! Here are some suggestions of bars for you to try while you're in the city!

,name,price_level,rating,vicinity
17,The Honey Well,2.0,4.7,"3604 Broadway, New York"
12,Anchor Wine Bar,2.0,4.6,"3508 Broadway, New York"
0,At The Wallace,1.0,4.5,"3612 Broadway, New York"
2,Uptown Bourbon,2.0,4.5,"3631 Broadway, New York"
3,Hogshead Tavern,2.0,4.5,"126 Hamilton Pl, New York"
7,Harlem Public,2.0,4.5,"3612 Broadway, New York"
1,The Grange,2.0,4.4,"1635 Amsterdam Ave, New York"
18,Showman's Jazz Club,NaN,4.4,"375 W 125th St, New York"
11,The Draft House,2.0,4.4,"3473 Broadway, New York"
10,Stan's Sports Bar,NaN,4.4,"836 River Ave, Bronx"
9,El Porton Bar,2.0,4.4,"576 Southern Blvd, Bronx"
4,Charlies Bar & Kitchen,2.0,4.4,"112 Lincoln Ave, Bronx"
8,Harlem Nights,2.0,4.3,"2361 Adam Clayton Powell Jr Blvd, New York"
5,Coogans,2.0,4.2,"4015 Broadway, New York"
19,Lola Lola,NaN,4.1,"1306 St Nicholas Ave, New York"
15,Studio 735 Bar and Lounge,NaN,4.0,"735 St Nicholas Ave, New York"
16,Solace Bar & Grill,NaN,4.0,"3496 Broadway, New York"
14,Two Sha's,2.0,3.8,"2576 Third Ave, Bronx"
6,21 Bar,NaN,3.7,"4318 Broadway, New York"
13,Buffalo Wild Wings,2.0,3.3,"2319 Frederick Douglass Blvd, New York"

In [ ]:
# import requests
# import json 
# import pandas as pd
# Ask for input (which stadium are you visiting?)
# Set params (address and key)
# Pull from URL
# try and except to account for IndexError 
# Ask for input (what are you looking for?)
# response
# output 
# code for dataframe (specific column names)
# Print ("Welcome to the stadium. Here are some suggestions.") 
# Print dataframe